spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/sustc  # change this to your own jdbc url
    username: sustc  # change this to your own username (avoid using a superuser)
    password: sustc  # change this to your own password

---

benchmark:
  run-id: 1
